### ISSUE TITLE
suggestion to add three EBM papers

### ISSUE THREAD

**Issue by sndnyang** [yataobian/awesome-ebm#1]
Hi, I like this repo.

I hope you can add the following papers(no EBM in the title):

Towards Understanding the Generative Capability of Adversarially Robust Classifiers    ICCV 2021  oral
https://openaccess.thecvf.com/content/ICCV2021/papers/Zhu_Towards_Understanding_the_Generative_Capability_of_Adversarially_Robust_Classifiers_ICCV_2021_paper.pdf     https://arxiv.org/abs/2108.09093  

JEM++: Improved Techniques for Training JEM     ICCV 2021
https://arxiv.org/abs/2109.09032

**Comment by sndnyang** [comment]
[Yao Zhu, Jiacheng Ma, Jiacheng Sun, Zewei Chen, Rongxin Jiang, Zhenguo Li.  Towards Understanding the Generative Capability of Adversarially Robust Classifiers. IEEE International Conference on Computer Vision (ICCV).](http://arxiv.org/abs/2108.09093)

[Xiulong Yang & Shihao Ji. JEM++: Improved Techniques for Training JEM. IEEE International Conference on Computer Vision (ICCV). ](http://arxiv.org/abs/2109.09032)

**Comment by yataobian** [comment]
will add them.  Thanks for the suggestion!
